# Generated by Django 5.1.4 on 2025-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee')], default='pending', max_length=50),
        ),
    ]
