# Generated by Django 5.1.4 on 2025-01-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('user', 'user'), ('employee', 'employee')], default='user', max_length=50),
        ),
    ]
