# Generated by Django 5.1.4 on 2025-01-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
