# Generated by Django 5.1.4 on 2025-01-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Details', '0002_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover_letter',
        ),
    ]
