# Generated by Django 5.1.4 on 2025-01-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Details', '0003_remove_application_cover_letter'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employer_email',
            field=models.ManyToManyField(to='employee.employee'),
        ),
    ]
