# Generated by Django 5.1.4 on 2025-01-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Details', '0005_remove_application_employer_email_and_more'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='employee.employee'),
        ),
    ]
