# Generated by Django 5.1.4 on 2025-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='company_image',
            field=models.ImageField(default=1, upload_to='Job_Listings/images/'),
            preserve_default=False,
        ),
    ]
