# Generated by Django 5.1.4 on 2025-01-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Listings', '0002_joblisting_company_image'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
